title: "Napjaim a Balkánon"
description: "Balkáni utazások fotónaplója – egy nap egy kép, városok, tájak, történetek"
baseurl: "/fotoblog"
url: "https://havassy.github.io"

markdown: kramdown
theme: null
plugins:
  - jekyll-sitemap
